routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['role:admin']], function() {

          Route::get('campaign/create', 'CampaignController@create')->name('campaign-create');
          Route::post('campaign/create', 'CampaignController@doCreate')->name('campaign-do-create');
          Route::get('campaign/edit/{id}', 'CampaignController@edit')->name('campaign-edit');
          Route::post('campaign/edit', 'CampaignController@doEdit')->name('campaign-do-edit');
          Route::get('campaign/delete/{id}', 'CampaignController@delete')->name('campaign-delete');

          Route::get('/users', 'UserController@index')->name('user-index');
          Route::get('/user/{id}', 'UserController@view')->name('user-view');
          Route::get('user/{id}/status', 'UserController@status')->name('user-status');

          Route::post('user/{id}/grant', 'UserController@grant')->name('user-grant');
          Route::post('user/{id}/deny', 'UserController@deny')->name('user-deny');

          Route::get('/categories', 'CategoryController@index')->name('category-index');
          Route::get('category/delete/{id}', 'CategoryController@delete')->name('category-delete');
          Route::post('category/create', 'CategoryController@doCreate')->name('category-do-create');

          Route::get('campaign/configure/{id}', 'CampaignController@configure')->name('campaign-config');
          Route::post('campaign/configure', 'CampaignController@configurePost')->name('campaign-config-save');

          Route::get('campaign/configure/video/{id}', 'CampaignController@configureVideo')->name('campaign-config-video');
          Route::post('campaign/configure/video', 'CampaignController@configureVideoPost')->name('campaign-config-video-save');
          Route::post('campaign/configure/addconfig', 'CampaignController@configureAddPost')->name('campaign-config-add-save');
          Route::post('campaign/configure/video/remove/{id}', 'CampaignController@removeVideo')->name('campaign-config-video-remove');

          Route::get('campaign/configure/css/{id}', 'CampaignController@configureCss')->name('campaign-config-css');
          Route::post('campaign/configure/css', 'CampaignController@configureCssPost')->name('campaign-config-css-save');

          Route::get('campaign/configure/assets/{id}', 'CampaignController@configureAsset')->name('campaign-config-asset');

          Route::post('file/post/{id}/{name}', 'CampaignController@uploadFilePost')->name('campaign-upload-file-post');

});

Route::get('player/scripts/{id}/frame_objects.csv', 'PlayerController@csv')->name('player-csv');
Route::get('player/scripts/{id}/object.HotSpot.js', 'PlayerController@objects')->name('player-objects');
Route::get('player/css/{id}/common.css', 'PlayerController@commonCss')->name('player-common-css');
Route::get('player/css/{id}/custom.css', 'PlayerController@css')->name('player-css');
Route::get('player/core/{id}/encoded.js', 'PlayerController@core')->name('player-core');

Route::get('player/image/{id}/{imgid}', 'PlayerController@image')->name('player-image');

Route::get('player/redirect', 'PlayerController@redirect')->name('player-redirect');

Route::get('player/{name}/{id}/{context?}', 'PlayerController@index')->name('player-index');

Route::get('campaign/reports/{id}/{startdate?}/{enddate?}/{debug?}', 'CampaignController@view')->name('campaign-view');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Zizaco\Entrust\Traits\EntrustUserTrait;
use App\Role;

class User extends Authenticatable
{
    use Notifiable;
    use EntrustUserTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function roles(){
        return $this->belongsToMany('App\Role');
    }

    public function campaigns()
    {
        return $this->belongsToMany('App\Campaign');
    }

    public function isAdmin()
    {
        if(count($this->roles) > 0) {
          return ($this->roles[0]->name == "admin");
        } else {
          return false;
        }
    }

    public function getAccountAttribute()
    {
        if(count($this->roles) > 0) {
          return "<span>" . $this->roles[0]->display_name . "</span>";
        } else {
          return "<span class='label label-danger'>Not Defined</span>";
        }
    }

    public function getStatusAttribute()
    {
        if($this->confirmed) {
          return "<span class='label label-primary'>Activated</span>";
        } else {
          return "<span class='label label-danger'>Deactivated</span>";
        }

    }


}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Campaign;
use App\Role;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();
        return view('users.index',compact("users"));
    }

    public function view($id)
    {
        $user = User::find($id);
        return view('users.view',compact("user"));
    }

    public function status($id)
    {
        $user = User::find($id);
        $user_role = Role::where("name","=","user")->first();

        if($user->confirmed) {
           $user->detachRole($user_role);
           $user->confirmed = 0;
        } else {
           $role = Role::where("name","=","user");
           $user->attachRole($user_role);
           $user->confirmed = 1;
        }

        $user->save();

        return redirect()->route("user-index");

    }

    public function grant(Request $request, $id)
    {
            $cid = $request->input('campaign');

            $user = User::find($id);

            $user->campaigns()->syncWithoutDetaching([$cid]);


            return redirect('user/'.$id);
    }

    public function deny(Request $request, $id)
    {
            $cid = $request->input('campaign');

            $user = User::find($id);

            $user->campaigns()->detach([$cid]);


            return redirect('user/'.$id);
    }

    public function show(Category $category)
    {
        //
    }

    public function destroy(Category $category)
    {
        //
    }
}

resources/views/users/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <ol class="breadcrumb">
        <li><a href="/home">Home</a></li>
        <li class="active">Users</li>
    </ol>
    <div class="row">
      @foreach ($users as $user)
        <div class="col-md-4">
            <div class="panel panel-default">
              <div class="panel-heading">
                  <a href="{{route('user-view',["id" => $user->id])}}">{{$user->name}}</a>
              </div>
                <div class="panel-body">
                      <span class="glyphicon glyphicon-envelope" style="margin-right:10px"></span>Email : {{$user->email}} <br/>
                      <span class="glyphicon glyphicon-user" style="margin-right:10px"></span>Account : {!! $user->account !!}<br/>
                      <span class="glyphicon glyphicon-off" style="margin-right:10px"></span>Status : <a href="{{route('user-status',["id" => $user->id])}}">{!! $user->status !!}</a><br/>
                </div>
            </div>
        </div>

        @endforeach
    </div>
</div>
@endsection

resources/views/users/view.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
          <div class="col-lg-12">
                  <ol class="breadcrumb">
                    <li><a href="{{ route('home') }}">Home</a></li>
                    <li><a href="{{ route('campaign-create') }}">User</a></li>
                    <li class="active">#{{ $user->id }}</li>
                  </ol>
          </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="panel panel-default">
              <div class="panel-heading">
                  <a href="{{route('user-view',["id" => $user->id])}}">{{$user->name}}</a>
              </div>
                <div class="panel-body">
                      <span class="glyphicon glyphicon-envelope" style="margin-right:10px"></span>Email : {{$user->email}} <br/>
                      <span class="glyphicon glyphicon-user" style="margin-right:10px"></span>Account : {!! $user->account !!}<br/>
                      <span class="glyphicon glyphicon-off" style="margin-right:10px"></span>Status : <a href="{{route('user-status',["id" => $user->id])}}">{!! $user->status !!}</a><br/>
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Campaigns
                    <button type="button" class="btn btn-default pull-right btn-xs" data-toggle="modal" data-target="#myModal">
                          <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                    </button>
                </div>
                <div class="panel-body">
                      <ul class="list-group">
                        @if(!$user->isAdmin()):
                              @foreach ($user->campaigns as $camp)
                                  <li class="list-group-item">{{$camp->name}}
                                        {{ Form::model($user, array('method' => 'post', 'route' => array('user-deny', $user->id))) }}
                                        {{ Form::hidden('campaign', $camp->id) }}
                                        <button type="submit" class="btn btn-danger pull-right btn-xs" aria-label="Remove" style="position:relative;top:-22px">
                                                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                                        </button>
                                        {{ Form::close() }}
                                  </li>
                              @endforeach
                        @else:
                              <li class="list-group-item list-group-item-success">Admin users have access to any campaign</li>
                        @endif
                      </ul>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Grant access to a campaign</h4>
      </div>
      {{ Form::model($user, array('method' => 'post', 'route' => array('user-grant', $user->id))) }}
      <div class="modal-body">
         <div class="form-group">
              {{ Form::select('campaign', array_pluck(App\Campaign::all(), 'name', 'id') ,null, ['class' => 'form-control']) }}
          </div>
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Save</button>
      </div>
      {{ Form::close() }}
    </div>
  </div>
</div>
@endsection